version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: platform-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - platform-net
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  platform-net:
    driver: bridge

# volumes:
#   pgdata:
#     driver: local-persist
#     driver_opts:
#       mountpoint: /$HOME
