"""Add supplier table

Revision ID: 67d297b7c006
Revises: 271b6be71260
Create Date: 2025-06-08 19:34:05.671037

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67d297b7c006"
down_revision: Union[str, None] = "271b6be71260"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("contact_person", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supplier_email"), "supplier", ["email"], unique=True)
    op.create_index(op.f("ix_supplier_id"), "supplier", ["id"], unique=False)
    op.create_index(op.f("ix_supplier_name"), "supplier", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_name"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_id"), table_name="supplier")
    op.drop_index(op.f("ix_supplier_email"), table_name="supplier")
    op.drop_table("supplier")
    # ### end Alembic commands ###
