"""Add supplier_id to product table

Revision ID: c3c05607b95b
Revises: d8fed3de84eb
Create Date: 2025-06-08 20:06:39.681206

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3c05607b95b"
down_revision: Union[str, None] = "d8fed3de84eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("supplier_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "product", "supplier", ["supplier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_supplier_id_fkey", "product", type_="foreignkey")
    op.drop_column("product", "supplier_id")
    # ### end Alembic commands ###
